import fs from "node:fs";
import path from "node:path";
import type { Plugin, ResolvedConfig } from "vite";

const NOTE =
  "<!-- Generated by `npm run build` (vite-plugin-spa-fallback): a copy of index.html so static hosts that only support a custom error page can still boot the router on /services, /about, /contact, … Do not edit by hand. -->";

/**
 * Static hosts have no idea that `/about` is a client-side route. The primary fix lives
 * in `settings/config.toml` (`page-fallback`), but that key is only read by Wasmer's
 * Static Web Server. This plugin emits `404.html` next to `index.html` so hosts that
 * instead offer `error_page 404 /404.html` (GitHub Pages, nginx, S3 + CloudFront)
 * recover the same way: the app shell is served, the URL is left untouched, and React
 * Router renders the page the visitor actually asked for.
 */
export function spaFallback(): Plugin {
  let resolved: ResolvedConfig | undefined;

  return {
    name: "zenviolabs-spa-fallback",
    apply: "build",
    configResolved(config) {
      resolved = config;
    },
    closeBundle() {
      const root = resolved?.root ?? process.cwd();
      const rawOutDir = resolved?.build?.outDir ?? "dist";
      const outDir = path.isAbsolute(rawOutDir) ? rawOutDir : path.resolve(root, rawOutDir);

      const indexHtml = path.join(outDir, "index.html");
      if (!fs.existsSync(indexHtml)) {
        this.warn(`[spa-fallback] no ${indexHtml} — skipped emitting 404.html`);
        return;
      }

      const html = fs.readFileSync(indexHtml, "utf8");
      const withNote = /<!doctype html>/i.test(html)
        ? html.replace(/<!doctype html>/i, `<!doctype html>\n${NOTE}`)
        : `${NOTE}\n${html}`;
      fs.writeFileSync(path.join(outDir, "404.html"), withNote.endsWith("\n") ? withNote : `${withNote}\n`);

      const tomlPath = path.resolve(root, "settings/config.toml");
      const hasFallback =
        fs.existsSync(tomlPath) && /^\s*page-fallback\s*=/m.test(fs.readFileSync(tomlPath, "utf8"));
      if (!hasFallback) {
        this.warn(
          "[spa-fallback] settings/config.toml has no `page-fallback` — refreshing a sub-page will 404 on Wasmer Edge.",
        );
      }

      this.info("  + 404.html  (SPA fallback for static hosts)");
    },
  };
}
